---
name: Release app

on:
  push:
    branches:
      - '*'
    tags:
      - '!v*'
jobs:
  build-the-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v
      - name: build app
        run: docker build -f $(pwd)/app/Dockerfile $(pwd)/app
